# Generated by Django 2.0 on 2017-12-22 13:22

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_media',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.Post.get_upload_path),
        ),
    ]
