# Generated by Django 2.0 on 2017-12-29 08:50

import blogs.models
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_post_featured_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_media',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.Post.get_upload_path, validators=[utils.validators.ContentTypeValidator(accepted_types=['image/jpeg', 'image/png', 'image/gif', 'video/mpeg', 'video/quicktime', 'video/mp4']), utils.validators.MaxFileSizeValidator(max_size=1048576)]),
        ),
    ]
