# Generated by Django 2.0 on 2018-01-14 18:15

import blogs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20171229_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_media',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.Post.get_upload_path, validators=[utils.validators.ContentTypeValidator(accepted_types=['image/jpeg', 'image/png', 'image/gif', 'video/mpeg', 'video/quicktime', 'video/mp4']), utils.validators.MaxFileSizeValidator(max_size=1048576)], verbose_name='featured media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured_video',
            field=models.BooleanField(default=False, verbose_name='is featured video?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
