# Generated by Django 2.0 on 2018-01-14 18:37

import blogs.models
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20180114_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='artítulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_media',
            field=models.FileField(blank=True, null=True, upload_to=blogs.models.Post.get_upload_path, validators=[utils.validators.ContentTypeValidator(accepted_types=['image/jpeg', 'image/png', 'image/gif', 'video/mpeg', 'video/quicktime', 'video/mp4']), utils.validators.MaxFileSizeValidator(max_size=1048576)], verbose_name='imagen/vídeo destacado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
    ]
